---

- name: Ensure nginx is installed.
  apt:
    name: nginx
    state: latest

- name: 'Nginx setup: add index.html file'
  template:
    src: index.html
    dest: /var/www/html/index.html
  notify: nginx fix file permissions

- name: 'Nginx setup: add info.php file'
  template:
    src: info.php
    dest: /var/www/html/info.php
  notify: nginx fix file permissions

- name: Update default vhost
  template:
    src: vhost.conf
    dest: /etc/nginx/sites-available/default
  notify: restart nginx
