---
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: nginx fix file permissions
  file:
    path: "{{ nginx_home }}"
    state: directory
    recurse: yes
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0444'
  notify: nginx fix file permissions final

- name: nginx fix file permissions final
  file:
    path: "{{ nginx_home }}"
    state: directory
    recurse: yes
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: "{{ nginx_home_dir_mode }}"
